### ISSUE TITLE
filebot has switched to xz format

### ISSUE THREAD

**Issue by moesasji** [bassmadrigal/slackbuilds#2]
Your slackbuild for filebot no longer works for the latest release of filebot (4.7.5) because the format in the deb file has changed. Replacing the extracting command with

ar p $CWD/${PRGNAM}_${VERSION}_${DEBARCH}.deb data.tar.xz | tar xJ

makes it build and it appears to work (except for an error-message relating to gvfs)

btw) the link to the startup script on line 81 needs to be changed to /usr/share/filebot/filebot.sh for the newer version.

**Comment by bassmadrigal** [comment]
Thanks for the heads up. I'll get an updated version pushed out sometime this next week (maybe tonight, depending on what the wife has planned for Christmas Eve). At least the current version is still available and works :)

**Comment by bassmadrigal** [comment]
What gvfs error are you seeing? I haven't seen any, but I only use the GUI. I'm about to push this to SBo, but I'd like to ensure there aren't any other issues.

Feel free to open up another issue if you'd like.

**Comment by moesasji** [comment]
1) The issue I see is that it complains about /gvfs not being a valid directory. I currently have no clue why this happens, so no suggested fix.

from the command line: java.lang.IllegalArgumentException: /gvfs is not a valid directory

2) The way you create the launcher actually prevents filebot to use scripts, compare the output from:

filebot -script fn:sysinfo

to 

/usr/share/filebot/filebot.sh -script fn:sysinfo

The latter produces the expected output. The fix is to explicitly pass on the arguments by putting a "$@" behind the /usr/share/filebot/filebot in your launcher. Note that you need to add the "" as otherwise it would break filenames with spaces.

**Comment by bassmadrigal** [comment]
1. How are you running it that causes that error to come up? What is the command you're using? I was able to launch the GUI from the terminal without any error. I'm just trying to find out how to reproduce the issue. I also ran ```filebot -script fn:sysinfo``` (which caused me to find and fix the other issue you stated) and it says that gvfs is ok. I'm running a full install of Slackware64 14.2 with the stock gvfs-1.26.3 package and jdk-8u112 from SBo.

2. I noticed that earlier when I was trying to reproduce your issue and already fixed it in the commit right after the one that upgraded the SlackBuild to 4.7.5.

**Comment by moesasji** [comment]
I see that error both when launching the GUI and when running the cmd-line. In all likelyhood it is something in this install as I'm not running a full install of 14.2, but the MLED 14.2 version. For some reason I don't see a .gvfs in the home directory, which might explain this.

Anyway it appears just cosmetic, i.e. the program works for me.

**Comment by bassmadrigal** [comment]
Well, it seems to be working without errors on a full Slackware install, which is what SBo expects, so I suppose I can go ahead and submit it.

And that's good that it seems to be working fine even with the error. If you do notice anything that's broke, let me know and I can try and reproduce it.

**Comment by bassmadrigal** [comment]
Crap. Sorry about all the notifications. In the past, I had accidentally uploaded several source archives. I later deleted them and committed those changes, however, I realized that they still lived in git's history and caused my repo to be about 40MB when it should be less than 1MB. To remove those, you have to rewrite your history, which rewrites all your commits. So, when I force pushed them to github, it must've added the comments because all the rewritten commits have new hashes. Unfortunately, I'm still kinda new to git, so I screwed up a few of those updates, which required me to try again. I shouldn't have to do any of this again and there should be no further noise on this topic. Sorry for the hassle, and, if desired, feel free to unsubscribe from this thread if you haven't already.
