### ISSUE TITLE
Installing and unninstalling the generated package mess with my resolution forever

### ISSUE THREAD

**Issue by marcotaranta** [bassmadrigal/slackbuilds#4]
I'm using a Radeon R9 290X with Slackware 14.2 x64 and multilib, kernel 4.4.88 and xorg 1.18.
I've generated the package with the slackbuild script, installed it, and when I've rebooted, my resolution was 1920x1080 (my monitor is ultra wide, makes 2560x1080), and I couldn't change it to 2560x1080 even using gft and xrandr.
Then I've tried to unninstall the package, but now the problem is still there without the amdgpu-pro package installed, maybe some file is still installed? Or something was made to my installed kernel?

**Comment by bassmadrigal** [comment]
Sorry you've been having problems with this.

As far as I know, amdgpu-pro should uninstall cleanly, leaning no stray files, but I don't have a supported card to test things (testing has been done by others on the LQ forum).

But can you post your /var/log/Xorg.0.log to see if there's any obvious errors? If you're interested in debugging the amdgpu-pro driver as well, seeing the xorg log when that's loaded might provide some insight into why you can't change the resolution.

**Comment by marcotaranta** [comment]
Thank for the reply man.
I've found the problem, I'm using slack 14.2 which comes with Xorg 1.18 and the ABI of the amdgpu-pro module on version 17.40 is for the Xorg 1.19 (current?).
Since I'm not willing to change from stable to current, do you know which amdgpu-pro of yours can be installed in a slack 14.2 (Xorg 1.18.3 and kernel 4.4.88 rebuilt for CIK and SI amdgpu modules)? These infos about which version of Xorg and Kernel it was compiled is hard to find.

**Comment by bassmadrigal** [comment]
Oh, I didn't realize they finally added support for Xorg 1.19. Researching that, it looks like they added it with v17.30. I know a lot of people had been waiting on that. But that sucks they removed support for older versions. What a pain. Once I get home, I'll make a note that 17.40 will only work for -current (I don't have a SlackBuild for 17.30).

Anyway, we had someone trying to get [17.10](https://github.com/bassmadrigal/slackbuilds/tree/master/unfinished/amdgpu-pro-driver/17.10) working, but ran into some issues. However, I believe it was due to them running a 4.9 kernel, and 17.10 probably needed patches for the 4.9 kernel and I don't know enough to patch it.

But I know it compiles without issue on a 4.4 and hopefully works without issue. There was also extensive testing done on the [16.60](https://github.com/bassmadrigal/slackbuilds/tree/master/unfinished/amdgpu-pro-driver/16.60) version and that should work fine.

But just an FYI, there have been massive improvements to the open source driver (so much so that it [usually outperforms](https://www.phoronix.com/scan.php?page=article&item=amdgpu-1730-radeonsi&num=2) the amdgpu-pro driver), unfortunately, you won't see those improvements unless you're running -current. If you're feeling adventurous, that may be an idea, or you can at least look forward to the improvements when Slackware 15.0 is released (whenever that ends up being).

**Comment by marcotaranta** [comment]
I've tried the 17.10 yesterday with no luck, it failed to load the module for some reason (I didn't had much time to see) and reverted to Vesa.
I'll try to use 16.60 tonight and get back to you with the results!

**Comment by marcotaranta** [comment]
And yes, I like the FOSS driver, but I need the amdgpu-pro for OpenCL

**Comment by marcotaranta** [comment]
So, I just managed to get AMDGPU-PRO under Slack 14.2.
First you have to slackbuild the xorg 1.19 from current (rsync the x11 src folder in a current repository), then build a 4.9 latest kernel (used 4.9.75), and the slackbuild of the amdgpu-pro 17.40, ln -s /usr/share/X11/xorg.conf.d/10.amdgpu-pro.conf /etc/X11/xorg.conf.d/ and you're good to go, I'm at the time using the OpenCL to mine some altcoins.

Also, thanks for the help and the package, you're the best!

**Comment by bassmadrigal** [comment]
Sorry, I saw your message and intended to respond, but then forgot about it.

Are you sure you needed to symlink that 10.amdgpu-pro.conf file? Because X is supposed to load any files in /usr/share/X11/xorg.conf.d/ unless they're overridden by files in /etc/X11/xorg.conf.d/

But thanks for the confirmation it works and good job on getting everything up and running.
